name: Deploy Migrations to Production
on:
  push:
    branches: [main, master]
jobs:
  generate-database-production:
    runs-on: ubuntu-latest

    env:
    DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Generate Migration
        run: npx prisma migrate deploy --schema=./prisma/schema.prisma
